### PR TITLE
Resolve #70, bug fixes, and small visual adjustments

### LINKED ISSUE #70: buttons that are both pressed and hover should have a shadow effect
btnpressed
buttonpressedhovered

### PR DESCRIPTION
**Pull request by hohaicongthuan**
## What's changed:

- Button colours: slightly adjust button colours and add the shadow effect mentioned in #70.
- Progress bar: adjust progress bar colours.
- Fix tab behaviour: in Windows 7, when an inactive tab is clicked on, it will be switched to active as soon as the mouse button is down so I fixed that. However, the fix that I applied here doesn't distinguish between the left, right, and middle mouse buttons. (I'm not proficient enough in Javascript and I'm too lazy to google for a solution 👀)
- Fix a tab bug: here's the bug.
test

### CODE REVIEW

File: docs/script.js [hunk 1]
```diff
@@ -37,6 +38,85 @@ tabButtons.forEach((tabButton) => {
   });
 });
 
+// Tabs > Tabs Template
+const tabList_TabsTemp = document.querySelector("[aria-label='Tabs Template'");
```
Comment (khang-nd) [inline docs/script.js]: Some suggestions here.

- Since we're using `camelCase` for naming, let's follow this for consistency.
`tabList_TabsTemp` may change to `templateTabList`, `tabList_WinWTabs` may change to `windowTabList` etc. Up to you for the decision.
- (optional) The entire tab handling code block appears to be repetitive, we could rewrite it into 1 function and pass in the respective selectors, this way that function can be reused for handling several tabs without repeating and having a hard time naming the variables.

**Review by khang-nd — CHANGES_REQUESTED** [review]

File: gui/_progressbar.scss [hunk 2]
```diff
@@ -8,43 +8,61 @@
...
+  box-shadow: inset 0 0 0 1px #f3f3f388, 0 0 0 1px #eaeaea88;
   margin: 2px 0;
   overflow: hidden;
-  background: linear-gradient(
-      to right,
-      rgba(0, 0, 0, 0.1),
-      transparent 20%,
-      transparent 80%,
-      rgba(0, 0, 0, 0.1)
+  background: radial-gradient(
```
Comment (khang-nd) [inline gui/_progressbar.scss:14]: I can't really verify but for the marquee, it seems the color is too pale after this change. If you could share a screenshot of the actual marquee that looks like this, I can put my mind at ease 🙂

image

**Review by khang-nd — CHANGES_REQUESTED** [review]
Hi @hohaicongthuan, just some minor points, great stuff as usual.

File: docs/script.js [hunk 3]
```diff
@@ -1,14 +1,112 @@
...
+      .querySelectorAll("[role=tabpanel]")
+      .forEach((tabPanel) => tabPanel.setAttribute("hidden", true));
+    tabContainer
+      .querySelector(`[role=tabpanel]#${targetId}`)
+      .removeAttribute("hidden");
+  });
+});
+
+// Tabs > Tabs Template
+const tabList_TabsTemp = document.querySelector("[aria-label='Tabs Template']");
```
[the remark this answers is not in the document]
Comment (hohaicongthuan) [reply docs/script.js:42]: - Sure thing, I'll change that. By the way, have you ever considered writing coding style guidelines? It'll be helpful for future contributors to know which coding styles to follow.
- As I've stated before, Javascript is not my area of expertise, so yeah, I did notice that I did a lot of code repetition 😅. I'll see what I can do.

File: gui/_progressbar.scss (hunk 2 above)
Comment (hohaicongthuan) [reply gui/_progressbar.scss:14]: You are right, the colour is too pale. I'll fix it tomorrow.

Context | Image
:-:|:-: 
From Copy File Dialog | ProgressBarMarquee_CopyFileDialogue
From Windows Update | ProgressBarMarquee_WindowsUpdate

Also, I've just noticed that the shiny/reflective part at the top of the progress bar doesn't stretch when the entire bar is stretched vertically, so I'll fix it too.

ae fae4w afae fae faef

File: docs/script.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (khang-nd) [reply docs/script.js:42]: I actually never considered putting up any contributing guidelines since it's just a fun project, I don't wanna spend the extra effort making up "rules" that people would never bother reading and are forced to follow.

With that said, don't stress about complying with what I suggested, these are just minor points, since you have spent the time contributing, I just feel I need to review and provide proper feedback so you may see some value in your contribution in return. **Consistency** and **DRY** (Don't Repeat Yourself) are prolly the most fundamental standards in any programming language, not just JavaScript.

File: gui/_progressbar.scss (hunk 2 above)
Comment (khang-nd) [reply gui/_progressbar.scss:14]: Awesome, cheers mate 🙂

**Comment by hohaicongthuan** [comment]
I think it's good now.

**Review by khang-nd — APPROVED** [review]
Looking good now, thanks mate!
